[FRONT_TEMP]
algo_type        virtual
trip_sensor      msm_therm
set_point        0
set_point_clr    0
sensors          msm_therm pa_therm0 chg_therm bms
weights          110       100       85        110
offsets          -2000     -2000     -2000     -2000
sampling         10000
math             0
sys_temp

[REPORT-FRONT-TEMP]
algo_type        monitor
sampling         300000
sensor           FRONT_TEMP
thresholds       45000
thresholds_clr   43000
actions          report
action_info      1

[BACK_TEMP]
algo_type        virtual
trip_sensor      msm_therm
set_point        0
set_point_clr    0
sensors          msm_therm pa_therm0 chg_therm bms
weights          110       100       85        110
offsets          -1000     -1000     -1000     -1000
sampling         10000
math             0
sys_temp

[REPORT-BACK-TEMP]
algo_type        monitor
sampling         300000
sensor           BACK_TEMP
thresholds       45000
thresholds_clr   43000
actions          report
action_info      1

[SS-BACK-BATT]
algo_type        ss
sampling         5000
sensor           BACK_TEMP
device           battery
set_point        41000
set_point_clr    38000

[SS-CHG-BATT]
algo_type        ss
sampling         5000
sensor           chg_therm
device           battery
set_point        50000
set_point_clr    44000
time_constant    0

[SS-MSM-CLUSTER0]
algo_type        ss
sampling         1000
sensor           msm_therm
device           cluster0
set_point        43000
set_point_clr    41000
device_max_limit 1401600

[SS-GPU]
algo_type        ss
sampling         250
sensor           gpu
device           gpu
set_point        95000
set_point_clr    65000

[SS-POPMEM]
algo_type        ss
disable
sampling         250
sensor           pop_mem
device           cluster0
set_point        70000
set_point_clr    55000
time_constant    2

[MONITOR-CAMERA-MSM]
algo_type        monitor
sampling         1000
sensor           msm_therm
thresholds       52000 56000
thresholds_clr   47000 53000
actions          camera camera
action_info      1 2
